apiVersion: v1
kind: Secret
metadata:
  labels:
    idp: keycloak
  name: oidc
  namespace: headlamp
type: Opaque
stringData:
  callbackURL: http://headlamp.node-01/oidc-callback
  clientID: headlamp
  clientSecret: qM8VpilHa8RpmVXIQHzgq5MrcpiruqHK
  issuerURL: https://keycloak.node-01/realms/headlamp
  scopes: profile,email
  validatorClientID: headlamp
  validatorIssuerURL: https://keycloak.node-01/realms/headlamp
