apiVersion: v1
kind: Secret
metadata:
  name: oidc-spring-auth
  namespace: headlamp
type: Opaque
stringData:
  callbackURL: http://headlamp.node-01/oidc-callback
  clientID: headlamp
  clientSecret: change-me-with-real-client-secret
  issuerURL: https://spring-auth.node-01
  scopes: profile,email,groups
  validatorClientID: headlamp
  validatorIssuerURL: https://spring-auth.node-01
