apiVersion: v1
kind: Secret
metadata:
  labels:
    idp: spring-auth
  name: headlamp-proxy-kubeconfig
  namespace: headlamp
type: Opaque
stringData:  
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZaVENDQTAyZ0F3SUJBZ0lVRWtVaUcyQmNZUUdGOTE4bi9HL05xczBIc0Vzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hhM1ZpWlMxdmFXUmpMWEJ5YjNoNUxtNXZaR1V0TURFd0hoY05Nall3TkRJNApNRGcxTWpJeldoY05Nell3TkRJMU1EZzFNakl6V2pBaU1TQXdIZ1lEVlFRRERCZHJkV0psTFc5cFpHTXRjSEp2CmVIa3VibTlrWlMwd01UQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQU9FdWRod2YKT1hiSU1oSG5kYWFMRlFTc2JRWWVrRlMzdDhYRlJmeGtCVkFPaForRUJEVytJSlNIOHJXZHVCMmVjcktKbkh5Two1QWtZdW5jN2ZGY3NFYVB0c0pweHlKbjBsYnZXTVpnOFpIWGc1N1VkZkM2ZFNuR01CdXFubGttNVdObW45VHJXCjdxMTdISDM3OUpHOWpPNFBxRldqMXZyZlVFZ3E5YURRNVR0VDJjczJBWmRoRldWbVlNT0R0VlN3dlRuL25DZ2kKMXdHSmZpN3dTdUtlaUhYSGtIYjVWdHQvbkdWVDA1c0RYMlRHMjZoYmM3SnIzcngzVkdLYkhwNkE3OGZVaE1SSgpjdlRqUVdVL2M3VkFNMTByMmp5ODB5SXdIQzJyMm5sS2syeEFPa1RZM3lROURzYXAzb1NjZzkzL1RUZWRGNzB0CnJVNEhsWUtzRTZRbXB2YXlEaEZKQVBxeU55Vmg5MkV4Ump1Q3ozeTcrREUvWGhKa2tyMTU4MmcrY1gvUnNHYjEKQzNNRTZ1TDYwU1VTeGNpWGNnZjlpejFJemNsZEdxOCtDNmNrMHZJbCtKdXhoZ1hKdjJyLytmZ0pnNmIwbWZFVQoxNlcrLzc4ZkxHMG5hOUF3NDVQZFZiQVRZWVNrVGUrUloxSzl0QnRSeGhCWFhmM0kwVzFDL2s4VTlBZmRmSC9xCjlnZE5oRUZSRGVQbVNFN0ZENlRlTGNQVzlTUmVXUEVZOUZMaFhOekQxN3lEYWxRRXhvYk5tem9xWWkxM2FIb0UKcnd4dldEYUkxYTBaZjhTbnhxT080dVB2N1M3Y2dvWjBidERsVWMwMUFFUEhVbXp2a0Rnem1SNUhwYlBjOWNENgpxK1hwbTBTK1gxMjdKWFFjM3RQaTR2WGdCeGo5RWxPOG1Lc0hBZ01CQUFHamdaSXdnWTh3SFFZRFZSME9CQllFCkZJV2VYbzVpWmNJSW9QQ014SHhHUm5SQWR6RWZNQjhHQTFVZEl3UVlNQmFBRklXZVhvNWlaY0lJb1BDTXhIeEcKUm5SQWR6RWZNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdQQVlEVlIwUkJEVXdNNElYYTNWaVpTMXZhV1JqTFhCeQpiM2g1TG01dlpHVXRNREdDR0d0MVltVXRiMmxrWXkxd2NtOTRlUzVvWldGa2JHRnRjREFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQWdFQTF2SW44TVk2TUpndy90NGw0QTFGT1VnOHVYTm43YURORmtaOGo5NVFjckdGa1ZLeDhwN3gKQjJxTlBndVRYK0lMaC9ITXcweVVVSllGLzF3TlJLYjNsaXdsd1NMYzZqVWR2bi85VXRQN2l1NHFRUTJ1TmNnYwovb1o2Q3dZZWIzdWw5Vk1DRU1QOVQ4aVlxL2IzZFlLRk41Yk5OaTNpZmNqakhrT2JDWm5xdXhFOVZHd3pGUFlECmd5anNVTVc0RFVvOEJqY2k2UGJmR2IrRkJvT2tOdUhQaUlyRDlmeThSSk5kYzZleVBuM0E2akN0REs4RHRyU2QKeVlXVy81eVdHeUQvblVVVldhaUFGYVZ3SnU3TGJSdERjSUpzdWlZTG54UFIya1Q5UlVqcWNNbSsrQXRiTTJCQgp0VitsRkdKL2xiLzZ6eko3V2p6WFlsYy91MDZnUjBEVDNxSFd3ZzNmTEY3Z1hOZjJ1NGgvb0hoQkt3OTBvRzdSCktydVAva29lendTUlVvZDF1a2JDNnFsUFRYTEtUaEhHd1U2ZGZuek5WM0UySGEyOXhTalFKLy9ZcURVRXhQc2MKV3d1ZU5PWUE1KzNtbFk3TDNZYTBsVkdHNFE5enk3R2hUdmx6ekRTRG1jUFhXOW5aZmNaeS9mZThvRFFxTXRVaAo1bmMrTEdxYkFqWE95Umh0UUpWWTVWelliNDlCNXlFb01jRG1icFFGWFE4Wmc4N0hPSWV3bjFiU29GWU8xcDIyCnFsN2drck9PMzFQMXFaNVVEM0lpZEo2cXRhakdBUVJDbFo3ZVdoN3ZuaU5VWVJBaGFXZno4dUxOeEs4S2I2VDkKWUdXUTlacTlsVmw5aDU1SUpsNlF1ZFR6ZEVwbHhUYmxiZW8rZEFuQlNUVWFQMm0xTlVzNU1kUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          server: https://kube-oidc-proxy.headlamp
        name: kube-oidc-proxy
    contexts:
      - context:
          cluster: kube-oidc-proxy
          user: oidc
        name: kube-oidc-proxy
    current-context: kube-oidc-proxy
    users:
      - name: oidc
        user:
          auth-provider:
            name: oidc
            config:
              client-id: headlamp
              client-secret: change-me-with-real-client-secret
              idp-issuer-url: https://spring-auth.node-01
              scope: profile,email,groups
              useAccessToken: "true"
