apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
resources:
  - ../base
  - spring-auth-config.yaml  
  - spring-auth-deploy.yaml  
  - spring-auth-service.yaml
  - spring-auth-ingress.yaml
  - headlamp-oidc-secret.yaml  
  - headlamp-proxy-kubeconfig.yaml
patches:
  - path: kube-oidc-proxy-spring-auth.yaml
    target:
      kind: Deployment
      name: kube-oidc-proxy
  - path: headlamp-spring-auth.yaml
    target:
      kind: Deployment
      name: headlamp
