apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-oidc-proxy
  namespace: headlamp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-oidc-proxy
rules:
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras", "userextras/authentication.kubernetes.io/credential-id", "uids"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-oidc-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-oidc-proxy
subjects:
- kind: ServiceAccount
  name: kube-oidc-proxy
  namespace: headlamp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-oidc-proxy
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-oidc-proxy
  template:
    metadata:
      labels:
        app: kube-oidc-proxy
    spec:
      serviceAccountName: kube-oidc-proxy
      hostAliases:
      - ip: "192.168.222.146"
        hostnames:
        - "keycloak.node-01"
      containers:
      - name: kube-oidc-proxy
        image: ghcr.io/tremolosecurity/kube-oidc-proxy:1.0.11
        command:
        - /usr/bin/kube-oidc-proxy
        args:
        - --secure-port=8443
        - --tls-cert-file=/etc/tls/tls.crt
        - --tls-private-key-file=/etc/tls/tls.key
        - --oidc-issuer-url=https://keycloak.node-01/realms/headlamp
        - --oidc-client-id=headlamp
        - --oidc-username-claim=preferred_username
        - --oidc-groups-claim=groups
        - --oidc-ca-file=/etc/oidc/keycloak.crt
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
        - name: keycloak-crt
          mountPath: /etc/oidc
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: kube-oidc-proxy-tls
      - name: keycloak-crt
        secret:
          secretName: keycloak-crt
---
apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-proxy
  namespace: headlamp
spec:
  selector:
    app: kube-oidc-proxy
  ports:
  - port: 443
    targetPort: 8443
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-headlamp-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: hl-admins
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-headlamp-devs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: hl-devs
  apiGroup: rbac.authorization.k8s.io
